//API actions
export const FETCH_DATA_REQUEST='FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS='FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE='FETCH_DATA_FAILURE';

//Sort actions
export const SORT_AUTHOR_WISE='SORT_AUTHOR_WISE';
export const SORT_TITLE_WISE='SORT_TITLE_WISE'
export const SORT_PUBLISHER_WISE='SORT_PUBLISHER_WISE'